-- Hyprland configuration entry point.
-- Each module is loaded in an isolated Hyprland Lua scope.
hl.config({ autogenerated = false })

require("settings")
require("monitors")
require("autostart")
require("input")
require("keybinds")
require("windowrules")
