#preload = ~/.config/hypr/wall.jpg
#wallpaper = eDP-1,~/.config/hypr/wall.jpg
#preload = /home/hamool/Pictures/wall.jpg
#wallpaper = eDP-1,/home/hamool/Pictures/wall.jpg
#splash = false

wallpaper {
  monitor = 
    path = ~/.config/hypr/wall.jpg
    fit_mode = cover
}

splash = false
